// Generated by https://quicktype.io

export interface Params {
    package_id: number;
    temp_id: number;
    unique_id: number;
    proxy_user_id: number;
    is_regin: number;
    mode: string;
}
